
### update functionality testing

POST http://localhost:4004/v2/MroSrv/PricingComments
Content-Type: application/json;IEEE754Compatible=true

{
    "Pricing_Conditions_manufacturerCode":"6787688",
    "Pricing_Conditions_countryCode":"IN",
    "pricing_Notif_uuid" : "123bfa13-1048-4589-b984-dbacc1379cfb",
    "Comment":"Testing the pricing rejection"
}