
### update functionality testing

PUT http://localhost:4004/v2/MroSrv/VendorNotifications(guid'3ec07f21-04d7-470c-b676-d15641b1e26f')
Content-Type: application/json;IEEE754Compatible=true

{
    "Vendor_List_manufacturerCode":"12000",
    "Vendor_List_localManufacturerCode":"45555",
    "Vendor_List_countryCode":"IN",
    "status_code":"Approved"
}